CREATE TABLE IF NOT EXISTS bookings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    pickup_latlng TEXT NOT NULL,
    drop_off_latlng TEXT NOT NULL,
    pickup_address TEXT NOT NULL,
    pickup_address_name TEXT NOT NULL,
    drop_off_address TEXT NOT NULL,
    pickup_place_id TEXT NOT NULL,
    dropoff_place_id TEXT NOT NULL,
    drop_off_address_name TEXT NOT NULL,
    fare_charges DECIMAL(10,2) NOT NULL,
    discounted_fare DECIMAL(10,2) NOT NULL,
    distance DECIMAL(10,2),
    booking_id VARCHAR(255) NOT NULL UNIQUE,
    status ENUM('pending', 'confirmed', 'cancelled', 'completed') NOT NULL,
    payment_mode VARCHAR(50),
    directions TEXT,
    payment_token TEXT,
    payment_id VARCHAR(255),
    name VARCHAR(255) ,
    phone VARCHAR(50) ,
    selected_time  VARCHAR(50),
    payment_time TEXT,
    selected_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    INDEX idx_booking_id (booking_id),
    INDEX idx_user_id (user_id),
    INDEX idx_status (status),
    INDEX idx_payment_id (payment_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;